### ISSUE TITLE
Exe problem

### ISSUE THREAD

**Issue by limelect** [Embarcadero/DelphiFMX4Python#94]
Plz see 
https://en.delphipraxis.net/topic/10675-d4p_export_demo/
Either VCL or FMX cannot make an EXE with pyinstaller.exe
On GUIPY the script runs with no problem

**Comment by lmbelo** [comment]
@limelect you will find further instructions [here](https://github.com/Embarcadero/DelphiFMX4Python/tree/main/samples/Installer).
Let me know if this works for you.

**Comment by limelect** [comment]
No, However in GUIPY it workes
G:\Delphi Projects\Embarcadero\Delphi4PythonExporter-main\installer>pyinstaller delphifmxexecutable.spec

The 'pathlib' package is an obsolete backport of a standard library package and
is incompatible with PyInstaller. Please remove this package (located in c:\user
s\limelect\anaconda3\lib\site-packages) using
    conda remove
then try again.

Am I to delete and install again?

[delphifmxexecutable.py.txt](https://github.com/Embarcadero/DelphiFMX4Python/files/13717186/delphifmxexecutable.py.txt)
[delphifmxexecutable.spec.txt](https://github.com/Embarcadero/DelphiFMX4Python/files/13717187/delphifmxexecutable.spec.txt)
 it did not work

**Comment by limelect** [comment]
I am missing some ting where is the source name and location is it the delphifmx?

**Comment by lmbelo** [comment]
Simplify your test case... Install Python3.11, PyInstaller and DelphiFMX out of Conda and try again.

**Comment by limelect** [comment]
Is it supposed to be like that?

[delphifmxexecutable.spec.txt](https://github.com/Embarcadero/DelphiFMX4Python/files/13717545/delphifmxexecutable.spec.txt)

















?

**Comment by limelect** [comment]
I see on the net an answer

I've experienced the same problem. I managed to solve it by downgrading pyInstaller to 5.1 (from 5.8) without touching pathlib. An additional possibility to consider.

**Comment by lmbelo** [comment]
Try it on Python3.11 as I said.

**Comment by limelect** [comment]
someting happened tp PyInstaller

**Comment by limelect** [comment]
First i deleted the dir problem
pyinstaller workers now
BUt
1. where is the name of my program?

**Comment by limelect** [comment]
Ok I found the program name
BUt
G:\Delphi Projects\Embarcadero\Delphi4PythonExporter-main\installer\dist\delphif
mxexecutable>delphifmxexecutable.exe
Traceback (most recent call last):
  File "D4P_export_demo.py", line 13, in <module>
  File "D4P_export_demo.py", line 7, in main
  File "parent_window.py", line 12, in __init__
SystemError: <built-in method LoadProps of Parent_Form object at 0x02A4A070> ret
urned NULL without setting an error
[16136] Failed to execute script 'D4P_export_demo' due to unhandled exception!

I will check it with VCL

**Comment by limelect** [comment]
Ok lastly i did it with VCL I put all necesseri information
this is a window output not command line

G:\Delphi Projects\Embarcadero\Delphi4PythonExporter-main\installer\VCL\dist\de
phifmxexecutable>delphifmxexecutable.exe
Traceback (most recent call last):
  File "D4P_export_demo.py", line 13, in <module>
  File "D4P_export_demo.py", line 7, in main
  File "parent_window.py", line 12, in __init__
SystemError: <built-in method LoadProps of Parent_Form object at 0x029F8070> re
urned NULL without setting an error
[16956] Failed to execute script 'D4P_export_demo' due to unhandled exception!
[delphivclexecutable.spec.txt](https://github.com/Embarcadero/DelphiFMX4Python/files/13718182/delphivclexecutable.spec.txt)
[Project1.py.txt](https://github.com/Embarcadero/DelphiFMX4Python/files/13718193/Project1.py.txt)

**Comment by limelect** [comment]
Finaly it workes on VCL

**Comment by limelect** [comment]
But on FMX Error this is the project
Delphi4PythonExporter-main\Samples\Simple_Demo

**Comment by limelect** [comment]
where is --windowed in the script i do not want command line

**Comment by limelect** [comment]
Still something very wrong on vcl
I get an empty form
![Screenshot - 19_12_2023 , 19_58_36](https://github.com/Embarcadero/DelphiFMX4Python/assets/4199131/026a1165-df08-4db3-b321-8ab11a21797c)

[delphivclexecutable.spec.txt](https://github.com/Embarcadero/DelphiFMX4Python/files/13718891/delphivclexecutable.spec.txt)

![Screenshot - 19_12_2023 , 19_52_38](https://github.com/Embarcadero/DelphiFMX4Python/assets/4199131/d9afef98-712f-494c-976e-d7da541da7c1)

**Comment by lmbelo** [comment]
Make sure your script is getting the right path to the .pydfm file.

**Comment by limelect** [comment]
I made sure as I am a professional
I do not have any (on my 3 vcl demo) just an empty screen
P.S My site www.limelect.com with Delphi since Delphi #1

**Comment by lmbelo** [comment]
Hmm... I didn't get the point.

Anyway, I quick fixed your project and shared it here again.

[Pythone.zip](https://github.com/Embarcadero/DelphiFMX4Python/files/13720304/Pythone.zip)

**Comment by limelect** [comment]
Finally, it works great thanks
can you only explain to me the   datas= fields?
For the first 2, I understand the path to the library and the library name
of the others.
if I have more forms will this be included I guess
each form has this structure r"Unit1.pydfm".
and lastly the point what does it mean?

As for FMX, I will try to play with it as it has a problem too

I could not find any good information on data here
https://pyinstaller.org/en/stable/man/pyi-makespec.html

**Comment by limelect** [comment]
why the last comment go into our discussion?

**Comment by limelect** [comment]
First Thanks for your kind help
But unfortunately, I have some bad comments which do not concern you
1. I did not get any action with the exe button pressed edit>label
2. If so Delphivcl has no preference over QT designer which does the same
3. with my https://limelect.com/downloads/compile-ui-to-py-files/    compile UI>py
    PYinstaler is used very simply and does the same job
4.  I hope Embarcadero will read this and take some action with their PY output
5.  I have added a test program
6. if I am wrong about the output plz notify me

[my_vcl_test.zip](https://github.com/Embarcadero/DelphiFMX4Python/files/13739251/my_vcl_test.zip)
