### ISSUE TITLE
Error: No Registered EventHandler for events of type "TCellClick

### ISSUE THREAD

**Issue by blueskylu2008** [Embarcadero/DelphiFMX4Python#97]
*** Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)] on win32. ***
*** Remote Python engine is active ***
>>> 
*** Remote Interpreter Reinitialized ***
>>> 
*** Remote Interpreter Reinitialized ***
AttributeError: Error in setting property OnCellClick
Error: No Registered EventHandler for events of type "TCellClick
Traceback (most recent call last):
  File "E:\delphifmx6\iArchMgr4Cb.py", line 13, in <module>
    main()
  File "E:\delphifmx6\iArchMgr4Cb.py", line 7, in main
    Application.MainForm = iCenterMgrForm(Application)
  File "E:\delphifmx6\UnitMain.py", line 91, in __init__
    self.LoadProps(os.path.join(os.path.dirname(os.path.abspath(__file__)), "UnitMain.pyfmx"))
RuntimeError: Error reading StringGridSp1.OnCellClick: AttributeError: Error in setting property OnCellClick
Error: No Registered EventHandler for events of type "TCellClick
>>> 
![image](https://github.com/Embarcadero/DelphiFMX4Python/assets/66190997/216eeea3-4822-4378-95ca-011fd565f904)
![image](https://github.com/Embarcadero/DelphiFMX4Python/assets/66190997/35fda04a-8e22-4ffa-a277-4c4582c1d636)
I made just a simple project in c++builder fmx and used the Exporter to Python. When running without modification the UnitMain.py it get this Error.

**Comment by davemaster** [comment]
Greetings,

Have you the "simple project code", the version of our IDEs  ??  Thanks in advance
